# Generated by Django 4.2.2 on 2023-06-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_edu", "0002_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="user_id",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
