# Generated by Django 4.2.2 on 2023-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_edu", "0005_alter_choice_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="grade",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="choice",
            name="numeric_answer",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="choice",
            name="text_answer",
            field=models.CharField(default=False, max_length=200),
        ),
    ]
